#!/bin/sh -e

NAME=quagga

case "$1" in
    configure)
        if ! id $NAME > /dev/null 2>&1 ; then
            addgroup --quiet --force-badname $NAME
            adduser --quiet --system --disabled-password \
                --no-create-home --home /dev/null $NAME --ingroup $NAME
        fi

        # Maintain alphabetical order
	DIRECTORY=/etc/quagga
	if [ ! -d "$DIRECTORY" ]; then
	    mkdir -p "$DIRECTORY"
	    echo "$DIRECTORY created"
        fi
        chown -R $NAME:$NAME $DIRECTORY

	DIRECTORY=/var/state
	if [ ! -d "$DIRECTORY" ]; then
	    mkdir -p "$DIRECTORY"
	    echo "$DIRECTORY created"
        fi
	DIRECTORY=/var/state/quagga
	if [ ! -d "$DIRECTORY" ]; then
	    mkdir -p "$DIRECTORY"
	    echo "$DIRECTORY created"
        fi
        chown -R $NAME:$NAME $DIRECTORY
	DIRECTORY=/var/run
	if [ ! -d "$DIRECTORY" ]; then
	    mkdir -p "$DIRECTORY"
	    echo "$DIRECTORY created"
        fi
        chown -R $NAME:$NAME $DIRECTORY

	#setup zebra and bgpd config files
	SRC_FILE=/etc/zebra.conf.sample
	DST_FILE=/etc/quagga/zebra.conf
	cp $SRC_FILE $DST_FILE

	SRC_FILE=/etc/bgpd.conf.sample2
	DST_FILE=/etc/quagga/bgpd.conf
	cp $SRC_FILE $DST_FILE
    ;;

    *)
        echo "postinst called with unknown argument \`$1'" >&2
        exit 1
    ;;
esac

#DEBHELPER#

exit 0
